const categories = [
  { name: 'Burgers', description: 'Classic and premium burger options', sortOrder: 1 },
  { name: 'Pizza', description: 'Signature pizza selection', sortOrder: 2 },
  { name: 'North Indian', description: 'Paneer, chole, and hearty meals', sortOrder: 3 },
  { name: 'Snacks', description: 'Rolls, sandwiches, and quick bites', sortOrder: 4 },
  { name: 'Desserts', description: 'Sweet finishes and treats', sortOrder: 5 }
];

const foods = [
  {
    name: 'Veg Burger + Fries + Coke',
    description: 'Bestselling burger combo with fries and cold drink.',
    shortDescription: 'Veg burger combo',
    price: 160,
    originalPrice: 200,
    offerText: 'Flat 20% OFF',
    category: 'Burgers',
    images: ['photo/fd17.jpg'],
    tags: ['bestseller', 'combo', 'burger'],
    ingredients: ['veg patty', 'fries', 'coke'],
    isFeatured: true,
    stock: 60,
    preparationTime: 18,
    spicyLevel: 'mild'
  },
  {
    name: 'Mrgharita Pizza',
    description: 'Classic margherita style pizza with a premium offer.',
    shortDescription: 'Pizza offer',
    price: 200,
    originalPrice: 250,
    offerText: 'Flat 20% OFF',
    category: 'Pizza',
    images: ['photo/fd27.jpg'],
    tags: ['pizza', 'bestseller'],
    ingredients: ['cheese', 'sauce', 'pizza base'],
    isFeatured: true,
    stock: 40,
    preparationTime: 22,
    spicyLevel: 'mild'
  },
  {
    name: 'Special Paneer Masala Dosa',
    description: 'Paneer-loaded dosa with a crisp finish.',
    shortDescription: 'Paneer dosa',
    price: 144,
    originalPrice: 180,
    offerText: 'Flat 20% OFF',
    category: 'North Indian',
    images: ['photo/fd26.jpg'],
    tags: ['dosa', 'paneer'],
    ingredients: ['dosa batter', 'paneer', 'masala'],
    isFeatured: true,
    stock: 35,
    preparationTime: 20,
    spicyLevel: 'medium'
  },
  {
    name: 'Veg Biryani with Raita',
    description: 'Aromatic biryani served with cooling raita.',
    shortDescription: 'Biryani combo',
    price: 165,
    originalPrice: 220,
    offerText: 'Flat 25% OFF',
    category: 'North Indian',
    images: ['photo/fd25.jpg'],
    tags: ['biryani', 'combo'],
    ingredients: ['rice', 'vegetables', 'raita'],
    isFeatured: true,
    stock: 50,
    preparationTime: 28,
    spicyLevel: 'medium'
  },
  {
    name: 'Veg Crunchy Taco',
    description: 'Crispy taco filled with fresh vegetables and sauce.',
    shortDescription: 'Crunchy taco',
    price: 120,
    originalPrice: 150,
    offerText: 'Flat 20% OFF',
    category: 'Snacks',
    images: ['photo/fd24.jpg'],
    tags: ['taco', 'snack'],
    ingredients: ['taco shell', 'vegetables', 'sauce'],
    stock: 45,
    preparationTime: 14,
    spicyLevel: 'mild'
  },
  {
    name: 'Veg Roll',
    description: 'Quick vegetarian roll for on-the-go orders.',
    shortDescription: 'Veg roll',
    price: 72,
    originalPrice: 80,
    offerText: 'Flat 10% OFF',
    category: 'Snacks',
    images: ['photo/fd28.jpg'],
    tags: ['roll', 'snack'],
    ingredients: ['wrap', 'vegetables', 'sauce'],
    stock: 70,
    preparationTime: 12,
    spicyLevel: 'mild'
  },
  {
    name: 'Veg Noodles',
    description: 'Stir fried noodles with vegetables and seasoning.',
    shortDescription: 'Veg noodles',
    price: 105,
    originalPrice: 130,
    offerText: 'Flat 20% OFF',
    category: 'Snacks',
    images: ['photo/fd30.jpg'],
    tags: ['noodles', 'asian'],
    ingredients: ['noodles', 'vegetables', 'seasoning'],
    stock: 55,
    preparationTime: 16,
    spicyLevel: 'medium'
  },
  {
    name: 'Schezwan Fries Rice',
    description: 'Bold schezwan flavored rice with crispy fries.',
    shortDescription: 'Fries rice',
    price: 140,
    originalPrice: 200,
    offerText: 'Flat 30% OFF',
    category: 'Snacks',
    images: ['photo/fd31.jpg'],
    tags: ['rice', 'schezwan'],
    ingredients: ['rice', 'fries', 'schezwan sauce'],
    stock: 44,
    preparationTime: 18,
    spicyLevel: 'spicy'
  },
  {
    name: 'Ice Cream',
    description: 'Classic dessert item with a smooth finish.',
    shortDescription: 'Dessert',
    price: 60,
    originalPrice: 100,
    offerText: 'Upto 40% OFF',
    category: 'Desserts',
    images: ['photo/fd6.jpg'],
    tags: ['dessert', 'sweet'],
    ingredients: ['milk', 'sugar'],
    stock: 90,
    preparationTime: 5,
    spicyLevel: 'mild'
  }
];

module.exports = { categories, foods };
